#!/usr/bin/env python

import os
import sys

from jet9cmd import Jet9Cmd, Jet9CmdError

if __name__ == "__main__":

    cmd = Jet9Cmd(progname=sys.argv[0], version="0.1", mod_dir="mods")

    if len(sys.argv) == 1 or sys.argv[1] == "--help" or sys.argv[1] == "-h":
        cmd.print_help()
        sys.exit(0)

    elif sys.argv[1] == "help" and len(sys.argv) > 2:
        cmd.print_help(module=sys.argv[2])
        sys.exit(0)

    try:
       sys.exit(cmd.process_cmd(sys.argv[1:]))

    except Jet9CmdError as e:
        print str(e)
        sys.exit(1)

